# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b93676b849cbe273699214ece1dd7c7aa027ab7f09b51c11ab6f65f5dfc52c529432d2498f995fe167c7ffec1dccd2cc6e4a60830f9191e9d6c87cf1a435d789

test:
  secret_key_base: c3dd1da15f9648d08d10c281134ac0fd08d893e93af9ad24e69bb24f32707768064bb87510d95a311b8e3fd1e6da6d8135f8ed2d4deb6188e14a5a860dc3e743

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
